CC = gcc
CFLAGS = -Wall -g

all: programa1 programa2 programa3

programa1: programa1.o

programa2: programa2.o

programa3: programa3.o

programa1.o: programa1.c

programa2.o: programa2.c

programa3.o: programa3.c


clean:
	rm programa1 programa2 programa3 *.o
